version: '3.7'
services:
#################
# BACKEND IMAGE #
#################
    backend:
        build:
            context: ./cryptolab-backend
            dockerfile: Dockerfile
        image: cryptolab-backend
        ports:
            - "3000:3000"
        command: ["npm", "run", "start:dev"]
        networks:
            - cryptolab
#################
# FRONTEND IMAGE #
#################
    frontend:
        build:
            context: ./cryptolab-frontend
            dockerfile: Dockerfile
        image: cryptolab-frontend
        ports:
            - "4200:4200"
        command: ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
        networks:
            - cryptolab
############
# NETWORKS #
############
networks:
    cryptolab:
